# HTTP 代理端口
port: CLASH_HTTP_PORT_PLACEHOLDER

# SOCKS5 代理端口
socks-port: CLASH_SOCKS_PORT_PLACEHOLDER

# Linux 和 macOS 的 redir 代理端口
redir-port: CLASH_REDIR_PORT_PLACEHOLDER

# 监听IP地址
bind-address: CLASH_LISTEN_IP_PLACEHOLDER

# 允许局域网的连接
allow-lan: CLASH_ALLOW_LAN_PLACEHOLDER

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# Clash 的 RESTful API
external-controller: 'EXTERNAL_CONTROLLER_PLACEHOLDER'

# RESTful API 的口令
secret: 'b&ZlKTte5OnEt2Sn'

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: /code/clash-dashboard

